<?php

// $feed['edugain'] = array(
// 	'url' => 'http://mds.edugain.org/',
// 	'certs' => array(
// 		'-----BEGIN CERTIFICATE-----
// MIIC1DCCAbygAwIBAgIETCJV1DANBgkqhkiG9w0BAQUFADAsMQ4wDAYDVQQKEwVHRUFOVDEaMBgG
// A1UEAxMRZWR1R0FJTiBTaWduZXIgQ0EwHhcNMTAwNjIzMTg0MzMyWhcNMTQwODAxMTg0MzMyWjAs
// MQ4wDAYDVQQKEwVHRUFOVDEaMBgGA1UEAxMRZWR1R0FJTiBTaWduZXIgQ0EwggEiMA0GCSqGSIb3
// DQEBAQUAA4IBDwAwggEKAoIBAQCRfl1zhkaFveJvJtS03bRIO3k77q2s5m+c6sQ83j71rIad+vGC
// O29S4JHBXHI/U57yNbNLgoKzl0MI4WQrs4KT/y+LPMFB9M0lNrALQd/op6PNc7CWKMN1yV8V/L74
// /vapRlb90gPVJABHmoAfQmjyMXLW38KLwzK1qEpKUIxPBfQMBawmh0gC2T5ndZndcMPpgsMXyG2A
// Z4QGSOt4tgpspjTSRY++X+gi9WUuWzsEHHdFhCR9UYQ6+1glMVheJjVmoD0b9V/KQ0BF/1zry2jf
// WlchFeILlWbWgiWsIBA4BPNHqFW42qGgUr9DI3FzRLHXqF2N2f592tzcTeDZ11ejAgMBAAEwDQYJ
// KoZIhvcNAQEFBQADggEBAGC8iCKBUzmNIhikaCImp8WIMoI9VMYf/iBGcovaujRW85BmVfE0qj2y
// G2BfuA8RkxX7wayvb6znA7HSuQHpdVoI6poPbaW5ynZy35G3pzKs7dyZo6oGivE1Cj7PqJHXLICJ
// in3pKWGfHLkkYa64B32pXy7t42Rlvn2uog5MEYCgo4jnfhxnw0iPFJTHEy3x/PJ5Yxe5o/fDIUXt
// bIb0R0Z6Tym34YsUQQvmT11vfPPsFVc6Nkda0xo2DBxaPfw3ieTojimmnToPLFJL9DEEWKSSrIZQ
// YYrop0ftnQRhkFiu2TMYXiIiwKgLXKz7VybtcIMjt/tClNsDWTlIxwwFnNo=
// -----END CERTIFICATE-----',
// 	),
// 	'processors' => array('refeds_rns'),
// );

$feed['switch'] = [
    "url" => "http://metadata.aai.switch.ch/metadata.switchaai.xml",
    "certs" => [
        "-----BEGIN CERTIFICATE-----
MIIEJjCCAw6gAwIBAgISSWITCHaaiMetadataSig2015MA0GCSqGSIb3DQEBCwUAMEYxCzAJBgNV
BAYTAkNIMQ8wDQYDVQQKEwZTV0lUQ0gxJjAkBgNVBAMTHVNXSVRDSGFhaSBNZXRhZGF0YSBTaWdu
aW5nIENBMB4XDTE1MDcxNTA3MDAwMFoXDTE4MDcxNTA2NTk1OVowQjELMAkGA1UEBhMCQ0gxDzAN
BgNVBAoTBlNXSVRDSDEiMCAGA1UEAxMZU1dJVENIYWFpIE1ldGFkYXRhIFNpZ25lcjCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAM8n4/5VbDFaBmI/xZXlMSVlmsQA/xB9cgzhunI8/Ifj
Cji8p3wwb53BrvosoBZXSKAsrQB736wuD3WKa5pd4zTbsV8AvAoL0Syx6Wc3rWxeZjrAnUfeE9yS
i40kg6iCZAcawdzZRm1FoEHBN50/ChfjZRCusc4a1qlverGnU4wozQMFClJm7Uf2JQ4X8/uexpF8
aDy0wfROhlCQFPo+fJA+gDjCn3axZRWAwozvE6A91ahgZtQ5Mq5T49tt8ogZMDmga32MPbcqxUJI
xgXQdlKiXqCSx4qtpywvjpegFLWtN+aY5qILfTPPnn37n+l1iBWiXtmoqt6g5tzoJVefdZsCAwEA
AaOCARAwggEMMA4GA1UdDwEB/wQEAwIHgDAdBgNVHQ4EFgQUNPJ4wplyT4usqy5df/+oGNoV2kgw
HwYDVR0jBBgwFoAUkAqRwu5oLhVuFP7yzr0RUYoeNd8wTAYDVR0fBEUwQzBBoD+gPYY7aHR0cDov
L2NybC5hYWkuc3dpdGNoLmNoL1NXSVRDSGFhaU1ldGFkYXRhU2lnbmluZ0NBMjAxNS5jcmwwVgYI
KwYBBQUHAQEESjBIMEYGCCsGAQUFBzAChjpodHRwOi8vY2EuYWFpLnN3aXRjaC5jaC9TV0lUQ0hh
YWlNZXRhZGF0YVNpZ25pbmdDQTIwMTUuY3J0MBQGA1UdIAQNMAswCQYHYIV0AQIGBzANBgkqhkiG
9w0BAQsFAAOCAQEAHfX45DAj4Raf+8DbGe2N/glCMfdsebB3MozN5746YWy/mBCTIYJLNpju5QZF
s8yphsyuTPvlQCr2WymilrkHgMYsdY7zvDIloIXaXtlIe+gYgpgjS/bXjwwAfn0/u9E6ST20z6DG
reBOwiua/PGURKbzIbaOroYUaQpoyaorabYiID9dmI/pfoZNBTJpWutvdvmK5LPB3kPpqDPNfjID
EA2UW5jNHVSkly4ZAS24Kiolq03AN0WCswxfzOt3+EuSH4/PoYc/tkDt01ztle3UxMbMjNGhTYs0
pmyt+QKURHW3ErHTLm/Vds6jyATa+eSrqedqpf5rDDiPrwD0wqTn7A==
-----END CERTIFICATE-----"
    ]
];

// $feed['kalmar2'] = array(
// 	'url' => 'http://kalmar2.org/simplesaml/module.php/aggregator/?id=kalmarcentral2&set=saml20-idp-remote&mimetype=application/xml',
// 	'certs' => array(
// 		'-----BEGIN CERTIFICATE-----
// MIIC+zCCAmSgAwIBAgIJALIv7VqXanQYMA0GCSqGSIb3DQEBBQUAMF0xCzAJBgNV
// BAYTAk5PMRIwEAYDVQQIEwlUcm9uZGhlaW0xEjAQBgNVBAcTCVRyb25kaGVpbTEQ
// MA4GA1UEChMHVU5JTkVUVDEUMBIGA1UEAxMLa2FsbWFyMi5vcmcwHhcNMDkxMDI2
// MDY1OTQyWhcNMTkxMDI2MDY1OTQyWjBdMQswCQYDVQQGEwJOTzESMBAGA1UECBMJ
// VHJvbmRoZWltMRIwEAYDVQQHEwlUcm9uZGhlaW0xEDAOBgNVBAoTB1VOSU5FVFQx
// FDASBgNVBAMTC2thbG1hcjIub3JnMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKB
// gQCi7bEwud2nKm9FSojyIFGXN1p2ZGpUOKSFxhmeicCujHQr1VYUhyXBDHONwPDt
// K9PdHFZ4lLgLKcAIqUcOoAWr65m/MJJVkX0P7TUTZ6OS4mDAo1NsZexZxTBof9hC
// wnFz9dbqEThqZw2UtyEDnhW6kCb6SBd+2Yjvd+YDZg8lfwIDAQABo4HCMIG/MB0G
// A1UdDgQWBBS2Sw/w4drjYrTiAHeWXyN2W1j1iDCBjwYDVR0jBIGHMIGEgBS2Sw/w
// 4drjYrTiAHeWXyN2W1j1iKFhpF8wXTELMAkGA1UEBhMCTk8xEjAQBgNVBAgTCVRy
// b25kaGVpbTESMBAGA1UEBxMJVHJvbmRoZWltMRAwDgYDVQQKEwdVTklORVRUMRQw
// EgYDVQQDEwtrYWxtYXIyLm9yZ4IJALIv7VqXanQYMAwGA1UdEwQFMAMBAf8wDQYJ
// KoZIhvcNAQEFBQADgYEALx5V6xKtPr7urC/QOWiHxUChQO+SJsbnlwIquwaEGgUf
// 0WrGidPu04zdv+VpKtR+/KZbIDuSWx0/AkbexiE9ZUzJ2GvdVSxr/uON9CtQIQTp
// 5WjZD0KaieaoIMy/w5shc+trjkV550g/MWFFqAjproXwHRrEQoAxWL0smtR1R/I=
// -----END CERTIFICATE-----',
// 	),
// );

// $feed['kalmar2test'] = array(
// 	'url' => 'http://test.kalmar2.org/simplesaml/module.php/aggregator/?id=kalmarcentral2test',
// 	'certs' => array(
// 		'-----BEGIN CERTIFICATE-----
// MIIC+zCCAmSgAwIBAgIJALIv7VqXanQYMA0GCSqGSIb3DQEBBQUAMF0xCzAJBgNV
// BAYTAk5PMRIwEAYDVQQIEwlUcm9uZGhlaW0xEjAQBgNVBAcTCVRyb25kaGVpbTEQ
// MA4GA1UEChMHVU5JTkVUVDEUMBIGA1UEAxMLa2FsbWFyMi5vcmcwHhcNMDkxMDI2
// MDY1OTQyWhcNMTkxMDI2MDY1OTQyWjBdMQswCQYDVQQGEwJOTzESMBAGA1UECBMJ
// VHJvbmRoZWltMRIwEAYDVQQHEwlUcm9uZGhlaW0xEDAOBgNVBAoTB1VOSU5FVFQx
// FDASBgNVBAMTC2thbG1hcjIub3JnMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKB
// gQCi7bEwud2nKm9FSojyIFGXN1p2ZGpUOKSFxhmeicCujHQr1VYUhyXBDHONwPDt
// K9PdHFZ4lLgLKcAIqUcOoAWr65m/MJJVkX0P7TUTZ6OS4mDAo1NsZexZxTBof9hC
// wnFz9dbqEThqZw2UtyEDnhW6kCb6SBd+2Yjvd+YDZg8lfwIDAQABo4HCMIG/MB0G
// A1UdDgQWBBS2Sw/w4drjYrTiAHeWXyN2W1j1iDCBjwYDVR0jBIGHMIGEgBS2Sw/w
// 4drjYrTiAHeWXyN2W1j1iKFhpF8wXTELMAkGA1UEBhMCTk8xEjAQBgNVBAgTCVRy
// b25kaGVpbTESMBAGA1UEBxMJVHJvbmRoZWltMRAwDgYDVQQKEwdVTklORVRUMRQw
// EgYDVQQDEwtrYWxtYXIyLm9yZ4IJALIv7VqXanQYMAwGA1UdEwQFMAMBAf8wDQYJ
// KoZIhvcNAQEFBQADgYEALx5V6xKtPr7urC/QOWiHxUChQO+SJsbnlwIquwaEGgUf
// 0WrGidPu04zdv+VpKtR+/KZbIDuSWx0/AkbexiE9ZUzJ2GvdVSxr/uON9CtQIQTp
// 5WjZD0KaieaoIMy/w5shc+trjkV550g/MWFFqAjproXwHRrEQoAxWL0smtR1R/I=
// -----END CERTIFICATE-----',
// 	),
// );
