<?php

// $feed['edugain'] = array(
// 	'url' => 'http://mds.edugain.org/',
// 	'certs' => array(
// 		'-----BEGIN CERTIFICATE-----
// MIIC1DCCAbygAwIBAgIETCJV1DANBgkqhkiG9w0BAQUFADAsMQ4wDAYDVQQKEwVHRUFOVDEaMBgG
// A1UEAxMRZWR1R0FJTiBTaWduZXIgQ0EwHhcNMTAwNjIzMTg0MzMyWhcNMTQwODAxMTg0MzMyWjAs
// MQ4wDAYDVQQKEwVHRUFOVDEaMBgGA1UEAxMRZWR1R0FJTiBTaWduZXIgQ0EwggEiMA0GCSqGSIb3
// DQEBAQUAA4IBDwAwggEKAoIBAQCRfl1zhkaFveJvJtS03bRIO3k77q2s5m+c6sQ83j71rIad+vGC
// O29S4JHBXHI/U57yNbNLgoKzl0MI4WQrs4KT/y+LPMFB9M0lNrALQd/op6PNc7CWKMN1yV8V/L74
// /vapRlb90gPVJABHmoAfQmjyMXLW38KLwzK1qEpKUIxPBfQMBawmh0gC2T5ndZndcMPpgsMXyG2A
// Z4QGSOt4tgpspjTSRY++X+gi9WUuWzsEHHdFhCR9UYQ6+1glMVheJjVmoD0b9V/KQ0BF/1zry2jf
// WlchFeILlWbWgiWsIBA4BPNHqFW42qGgUr9DI3FzRLHXqF2N2f592tzcTeDZ11ejAgMBAAEwDQYJ
// KoZIhvcNAQEFBQADggEBAGC8iCKBUzmNIhikaCImp8WIMoI9VMYf/iBGcovaujRW85BmVfE0qj2y
// G2BfuA8RkxX7wayvb6znA7HSuQHpdVoI6poPbaW5ynZy35G3pzKs7dyZo6oGivE1Cj7PqJHXLICJ
// in3pKWGfHLkkYa64B32pXy7t42Rlvn2uog5MEYCgo4jnfhxnw0iPFJTHEy3x/PJ5Yxe5o/fDIUXt
// bIb0R0Z6Tym34YsUQQvmT11vfPPsFVc6Nkda0xo2DBxaPfw3ieTojimmnToPLFJL9DEEWKSSrIZQ
// YYrop0ftnQRhkFiu2TMYXiIiwKgLXKz7VybtcIMjt/tClNsDWTlIxwwFnNo=
// -----END CERTIFICATE-----',
// 	),
// 	'processors' => array('refeds_rns'),
// );

$feed['kalmar2'] = array(
	'url' => 'http://kalmar2.org/simplesaml/module.php/aggregator/?id=kalmarcentral2&set=saml20-idp-remote&mimetype=application/xml',
	'certs' => array(
		'-----BEGIN CERTIFICATE-----
MIIC+zCCAmSgAwIBAgIJALIv7VqXanQYMA0GCSqGSIb3DQEBBQUAMF0xCzAJBgNV
BAYTAk5PMRIwEAYDVQQIEwlUcm9uZGhlaW0xEjAQBgNVBAcTCVRyb25kaGVpbTEQ
MA4GA1UEChMHVU5JTkVUVDEUMBIGA1UEAxMLa2FsbWFyMi5vcmcwHhcNMDkxMDI2
MDY1OTQyWhcNMTkxMDI2MDY1OTQyWjBdMQswCQYDVQQGEwJOTzESMBAGA1UECBMJ
VHJvbmRoZWltMRIwEAYDVQQHEwlUcm9uZGhlaW0xEDAOBgNVBAoTB1VOSU5FVFQx
FDASBgNVBAMTC2thbG1hcjIub3JnMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKB
gQCi7bEwud2nKm9FSojyIFGXN1p2ZGpUOKSFxhmeicCujHQr1VYUhyXBDHONwPDt
K9PdHFZ4lLgLKcAIqUcOoAWr65m/MJJVkX0P7TUTZ6OS4mDAo1NsZexZxTBof9hC
wnFz9dbqEThqZw2UtyEDnhW6kCb6SBd+2Yjvd+YDZg8lfwIDAQABo4HCMIG/MB0G
A1UdDgQWBBS2Sw/w4drjYrTiAHeWXyN2W1j1iDCBjwYDVR0jBIGHMIGEgBS2Sw/w
4drjYrTiAHeWXyN2W1j1iKFhpF8wXTELMAkGA1UEBhMCTk8xEjAQBgNVBAgTCVRy
b25kaGVpbTESMBAGA1UEBxMJVHJvbmRoZWltMRAwDgYDVQQKEwdVTklORVRUMRQw
EgYDVQQDEwtrYWxtYXIyLm9yZ4IJALIv7VqXanQYMAwGA1UdEwQFMAMBAf8wDQYJ
KoZIhvcNAQEFBQADgYEALx5V6xKtPr7urC/QOWiHxUChQO+SJsbnlwIquwaEGgUf
0WrGidPu04zdv+VpKtR+/KZbIDuSWx0/AkbexiE9ZUzJ2GvdVSxr/uON9CtQIQTp
5WjZD0KaieaoIMy/w5shc+trjkV550g/MWFFqAjproXwHRrEQoAxWL0smtR1R/I=
-----END CERTIFICATE-----',
	),
);

// $feed['kalmar2test'] = array(
// 	'url' => 'http://test.kalmar2.org/simplesaml/module.php/aggregator/?id=kalmarcentral2test',
// 	'certs' => array(
// 		'-----BEGIN CERTIFICATE-----
// MIIC+zCCAmSgAwIBAgIJALIv7VqXanQYMA0GCSqGSIb3DQEBBQUAMF0xCzAJBgNV
// BAYTAk5PMRIwEAYDVQQIEwlUcm9uZGhlaW0xEjAQBgNVBAcTCVRyb25kaGVpbTEQ
// MA4GA1UEChMHVU5JTkVUVDEUMBIGA1UEAxMLa2FsbWFyMi5vcmcwHhcNMDkxMDI2
// MDY1OTQyWhcNMTkxMDI2MDY1OTQyWjBdMQswCQYDVQQGEwJOTzESMBAGA1UECBMJ
// VHJvbmRoZWltMRIwEAYDVQQHEwlUcm9uZGhlaW0xEDAOBgNVBAoTB1VOSU5FVFQx
// FDASBgNVBAMTC2thbG1hcjIub3JnMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKB
// gQCi7bEwud2nKm9FSojyIFGXN1p2ZGpUOKSFxhmeicCujHQr1VYUhyXBDHONwPDt
// K9PdHFZ4lLgLKcAIqUcOoAWr65m/MJJVkX0P7TUTZ6OS4mDAo1NsZexZxTBof9hC
// wnFz9dbqEThqZw2UtyEDnhW6kCb6SBd+2Yjvd+YDZg8lfwIDAQABo4HCMIG/MB0G
// A1UdDgQWBBS2Sw/w4drjYrTiAHeWXyN2W1j1iDCBjwYDVR0jBIGHMIGEgBS2Sw/w
// 4drjYrTiAHeWXyN2W1j1iKFhpF8wXTELMAkGA1UEBhMCTk8xEjAQBgNVBAgTCVRy
// b25kaGVpbTESMBAGA1UEBxMJVHJvbmRoZWltMRAwDgYDVQQKEwdVTklORVRUMRQw
// EgYDVQQDEwtrYWxtYXIyLm9yZ4IJALIv7VqXanQYMAwGA1UdEwQFMAMBAf8wDQYJ
// KoZIhvcNAQEFBQADgYEALx5V6xKtPr7urC/QOWiHxUChQO+SJsbnlwIquwaEGgUf
// 0WrGidPu04zdv+VpKtR+/KZbIDuSWx0/AkbexiE9ZUzJ2GvdVSxr/uON9CtQIQTp
// 5WjZD0KaieaoIMy/w5shc+trjkV550g/MWFFqAjproXwHRrEQoAxWL0smtR1R/I=
// -----END CERTIFICATE-----',
// 	),
// );
